"""remove genre column

Revision ID: 0e7729303c7d
Revises: 7025c99c1e50
Create Date: 2026-06-05 23:08:17.998481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7729303c7d'
down_revision: Union[str, Sequence[str], None] = '7025c99c1e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
